forge 'https://forgeapi.puppetlabs.com'

mod 'example42-apache'
mod 'willdurand-composer'

mod 'mstrauss-editfile',    git: 'https://github.com/mstrauss/puppet-editfile'

mod 'billiam-adminer',    path: 'private/adminer'
mod 'billiam-git',        path: 'private/git'
mod 'billiam-mysql',      path: 'private/mysql'
mod 'billiam-php5',       path: 'private/php5'
mod 'billiam-postgres',   path: 'private/postgres'
mod 'billiam-site',       path: 'private/site'
mod 'billiam-xdebug',     path: 'private/xdebug'
